### ISSUE TITLE
To be excluded dependencies

### ISSUE THREAD

**Issue by Vampire** [iskrenyp/spock-goodies#1]
Someone mentioned your goodies, so I added the two finished ones to https://github.com/spockframework/spock/wiki/Third-Party-Extensions. (Feel free to add future ones yourself to spread knowledge about them).

While doing so I've seen that you expect your users to explicitly exclude Groovy and Spock dependencies in both your extensions.
I'd like to suggest that you change in your build script the configuration to which you add them from `implementation` to `compileOnly`, then you will have them at compile time, but they are no transitive dependencies and your users don't need to manually exclude them.

**Comment by iskrenyp** [comment]
Yes, many thanks for the reminder! Will be fixed in the next commit.
